customer_txt_first_name = '//input[@name="first_name"]'
customer_txt_last_name = '//input[@name="last_name"]'
customer_txt_email = '//input[@name="email"]'
customer_txt_birthday = '//input[@name="birthday"]'
customer_txt_address = '//textarea[@name="address"]'
customer_txt_city = '//input[@name="city"]'
customer_txt_state = '//input[@name="stateAbbr"]'
customer_txt_zipcode = '//input[@name="zipcode"]'
customer_txt_password = '//input[@name="password"]'
customer_txt_confirm_password = '//input[@name="confirm_password"]'
customer_btn_submit = '//button[@type="submit"]'


nav_btn_customers = '(//p[text()="Customers"])[2]'
customers_btn_create = '//a[@aria-label="Create"]'
table = '//table//tbody//tr'

# created_customer_first_name = '//input[@name="first_name"]'
# created_customer_first_name_value = '//input[@name="first_name"]/@value'
# created_customer_last_name_value = '//input[@name="last_name"]/@value'
# created_customer_email_value = '//input[@name="email"]/@value'
# created_customer_address_value = '//textarea[@name="address"]/@value'
# created_customer_city_value = '//input[@name="city"]/@value'
# created_customer_state_value = '//input[@name="stateAbbr"]/@value'
# created_customer_birthday_value = '//input[@name="birthday"]/@value'
# created_customer_zipcode_value = '//input[@name="zipcode"]/@value'
# created_customer_password_value = '//input[@name="password"]/@value'
# created_customer_confirm_password_value = '//input[@name="confirm_password"]/@value'